POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "tadeu@email.com",
    "password": "12346",
    "role": "ADMIN"
}

### 

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "ursula@email.com",
    "password": "432121"
}
