POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Marina",
    "email": "mar@email.com",
    "password": "minhasenha123"
}

###

GET http://localhost:3003/users
Content-Type: application/json

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Celular",
    "price": 2000.00,
    "imageUrl": "https://images.unsplash.com/photo-1560617544-b4f287789e24?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
}

###

GET http://localhost:3003/products
Content-Type: application/json 

###

POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "1644517573143",
    "productId": "1644609951422",
    "quantity": 1
}

### 

GET http://localhost:3003/users/1644517573143/purchases
Content-Type: application/json 

