POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Rodrigo",
    "email": "ro@email.com",
    "password": "minhasenha123"
}

###

GET http://localhost:3003/users
Content-Type: application/json

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Microphone",
    "price": 850.00,
    "imageUrl": "https://images.unsplash.com/photo-1585102651425-8caf7848e44b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=581&q=80"
}

###

GET http://localhost:3003/products?search=mi
Content-Type: application/json 

###

POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "1644753076252",
    "productId": "1644752522133",
    "quantity": 3
}

### 

GET http://localhost:3003/users/:user_id/purchases
Content-Type: application/json 

