POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Melissa",
    "email": "mel@email.com",
    "password": "minhasenha123"
}

###

GET http://localhost:3003/users
Content-Type: application/json

###


