POST http://localhost:3003/class
Content-Type: application/json

{
    "name": "Turma D"
}

###

POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "Karen",
    "email": "ka@email.com",
    "birth_date": "08/07/1988",
    "class_id": "CID1645316032953"
}

### 

POST http://localhost:3003/teacher
Content-Type: application/json

{
    "name": "Karen",
    "email": "ka@email.com",
    "birth_date": "08/07/1988",
    "class_id": "CID1645316147382"
}